### ISSUE TITLE
IPC tests fail when running in windows 7

### ISSUE THREAD

**Issue by hiendv** [nanomsg/mangos#110]
Because of https://github.com/microsoft/go-winio/issues/155 issue, IPC transport tests in Windows 7 are also hanging.
E.g.
```bash
go test ./transport/ipc/ -run TestIpcListenAndAccept
```

Environment
- OS: Windows 7 Professional x64
- Go: 1.12.7 windows/amd64

**Comment by gdamore** [comment]
Thanks for bringing this to my attention.

I don't have a Windows 7 system.  Does this reproduce on Windows 10?

**Comment by gdamore** [comment]
I'm using 1.12.3 on Windows 10 -- it seems to work fine there.  I'm honestly not sure if I really want to get too wrought up about this failing on Windows 7 -- given that Windows 7 will be EOL in January (just 4 months from now).

**Comment by hiendv** [comment]
I can confirm it’s working fine with Windows 10. I know it maybe too much to ask but the proportion of Windows 7 users is still large for us. If you can give us the pointer, I think we can help with something.

**Comment by hiendv** [comment]
I know the different start from win-io but just can’t really understand their implementation. We tried go-npipe, it’s working.

**Comment by gdamore** [comment]
I can’t really help much. I don’t have any windows 7 systems I can even try to test on.

**Comment by gdamore** [comment]
Windows 7 is EOL.  I am not even going to try to address fixing a problem that doesn't occur on more recent releases.  Sorry.
