### ISSUE TITLE
Pipeline example not working

### ISSUE THREAD

**Issue by rodriguise** [nanomsg/mangos#111]
Using the compiled example and running `run.sh`

```
NODE1: SENDING "Hello, World."
NODE1: SENDING "Goodbye."
```

NODE0 does not receive the packets, i.e. `sock.Recv()` never returns.

os: macOS 10.14.5
go version: go1.12.7 darwin/amd64

**Comment by gdamore** [comment]
So there is a bug here, which is that the send program is simply exiting too quickly, before the message goes out over the wire.

The best thing to do is to add a slight delay before exiting -- stay tuned for an update on that.
