### ISSUE TITLE
How to create a connection pool？please

### ISSUE THREAD

**Issue by lookCLZ** [nanomsg/mangos#141]
How to create a connection pool？please，thank you very much!

**Comment by gdamore** [comment]
You don't need to.  Mangos will manage multiple connections under the hood for you.  Simply have a server do Listen() on the socket (e.g. a rep socket) then do Dial() from the client side from as many clients as you want.

If you want to run the operations truly in parallel (meaning long running RPCs for example) you might want to look at OpenContext() on the server side, and have multiple go routines each with their own context.   I believe there's a demo program for that in the repo.
