### ISSUE TITLE
OptionSubscribe topic uses reference instead of copy

### ISSUE THREAD

**Issue by chaowang101** [nanomsg/mangos#177]
When calling SetOption to subscribe to a prefix, it takes in a reference of the user provided prefix instead of a copy, which could cause race condition and allow user to change the subscription on the fly.

**Comment by gdamore** [comment]
This behavior is not a feature, but a design defect.

I will fix it.  I hope nobody is depending on it.  (Someday we might want to use a trie and that wouldn't work if people were relying on this bug.)
