### ISSUE TITLE
Panic in Message.Dup

### ISSUE THREAD

**Issue by hyprnick** [nanomsg/mangos#179]
I'm getting a panic in a client when I restart a server it is connected to:  

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x950c39]

goroutine 151 [running]:
nanomsg.org/go/mangos/v2.(*Message).Dup(0x0, 0x40c1c6)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.7/message.go:124 +0x29
nanomsg.org/go/mangos/v2/protocol/req.(*socket).send(0xc000251680)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.7/protocol/req/req.go:92 +0x189
nanomsg.org/go/mangos/v2/protocol/req.(*socket).AddPipe(0xc000251680, 0xc3e1a0, 0xc000061bc0, 0x0, 0x0)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.7/protocol/req/req.go:487 +0x13a
nanomsg.org/go/mangos/v2/internal/core.(*socket).addPipe(0xc00023e360, 0x7f595fadaca0, 0xc000061b60, 0xc000251920, 0x0)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.7/internal/core/socket.go:78 +0x176
nanomsg.org/go/mangos/v2/internal/core.(*dialer).dial(0xc000251920, 0xc000061401, 0x0, 0x0)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.7/internal/core/dialer.go:173 +0x337
nanomsg.org/go/mangos/v2/internal/core.(*dialer).redial(...)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.7/internal/core/dialer.go:215
created by time.goFunc
	/usr/local/Cellar/go/1.13.5/libexec/src/time/sleep.go:168 +0x44
```

### Setup
- Kubernetes
- Two pods with REP socket to load balance requests
- Client REQ socket dials to headless service e.g. `mystatefulset.default.svc.cluster.local:8000`

Requests properly alternate between each replica in the stateful set.  When one server pod is deleted, the _client_ dumps the above panic.  

- Is this the proper way to setup load balancing? Should I list the exact endpoint instead?  `dig` would show multiple IPs for this address.
- How can I get a status log when a client connects/disconnects in the Dialer during a redial attempt?  
- How would you handle removing members of a load balancing set?  I only see `socket.Dial(url)` to connect to more.  

This is an amazing project! Thank you 💯

**Comment by gdamore** [comment]
It sounds like this is a bug.  I want to confirm that you are using v2.0.7.

I made some changes to the implementation of Dup() to attempt to gain some performance and reduce copying -- it is possible that somehow I've botched that.  What it looks like is happening is that when you disconnect, the pipe reconnects automatically, and that is supposed to send an automatic retry of any outstanding request.

You can probably revert to an earlier (say 2.0.5 or so) version to avoid this problem.  I'll see if I can come up with a real fix shortly.  It should be relatively easy to reproduce.

**Comment by hyprnick** [comment]
Yes, using v2.0.7 and go 1.13.  

Am I dialing correctly?  I would like to avoid having to specify each pod to connect to as that changes during runtime.  

It also looks like I was missing a `defer socket.Close()`.

**Comment by gdamore** [comment]
I can't tell about your dialing logic as I don't see your code.  Nothing in your stack trace suggests a problem.

**Comment by gdamore** [comment]
So the good news is that I'm pretty sure I understand what is happening.  The bad news is:

1. The earlier v 2.0 releases probably aren't going to help.  The bug isn't in the new Dup logic, but rather in the 2.x rewrite of REQ

2. I'm having a difficult time figuring out how to reproduce this for testing in the context of a regular test suite.  That doesn't mean I can't fix it -- I just want to spent a bit of time to make sure that I can validate the fix.

**Comment by gdamore** [comment]
I think I have a solution.  Essentially, we have to be careful not to re-queue a broadcast while an attempt is already queued.  This can occur if we push too hard on the retries.

**Comment by hyprnick** [comment]
@gdamore Not seeing the panic anymore, thanks for the quick turnaround!

**Comment by hyprnick** [comment]
@gdamore Looks like I spoke too soon: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8c97b9]

goroutine 584 [running]:
nanomsg.org/go/mangos/v2.(*Message).Dup(0x0, 0x40c1c6)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/message.go:157 +0x29
nanomsg.org/go/mangos/v2/protocol/req.(*socket).send(0xc000313020)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/protocol/req/req.go:89 +0x13d
nanomsg.org/go/mangos/v2/protocol/req.(*socket).AddPipe(0xc000313020, 0xc3e500, 0xc000270120, 0x0, 0x0)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/protocol/req/req.go:489 +0x13a
nanomsg.org/go/mangos/v2/internal/core.(*socket).addPipe(0xc00022e1b0, 0x7f497e1a9280, 0xc0001a3020, 0xc0000d2de0, 0x0)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/internal/core/socket.go:78 +0x176
nanomsg.org/go/mangos/v2/internal/core.(*dialer).dial(0xc0000d2de0, 0xc00058af01, 0x0, 0x0)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/internal/core/dialer.go:173 +0x337
nanomsg.org/go/mangos/v2/internal/core.(*dialer).redial(...)
	/Users/nick/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/internal/core/dialer.go:215
created by time.goFunc
	/usr/local/Cellar/go/1.13.5/libexec/src/time/sleep.go:168 +0x44
```

**Comment by strowk** [comment]
I'm on 2.0.8, where fix https://github.com/nanomsg/mangos/commit/79daf1feba6dd2108c02bad0f681dcef712d99e5 is present and Dup still panics 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x0 addr=0x0 pc=0x0]

goroutine 53 [running]:
nanomsg.org/go/mangos/v2.(*Message).Dup(0x0, 0x100000000)
C:/Users/strow/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/message.go:157 +0x2
```

points to this line:
https://github.com/nanomsg/mangos/blob/master/message.go#L157 , which seems to be the same as in previous version (2.0.7 from ticket description) :
https://github.com/nanomsg/mangos/blob/v2.0.7/message.go#L124

@gdamore are you sure it was fixed?

**Comment by strowk** [comment]
I added a few lines to the problem place:
```
	if m == nil {
		log.Printf("Ooops, message is nil!!!, now that's weird")
	}
	if m.Body == nil {
		log.Printf("Ooops, body is nil!!!")
	}
	dup := NewMessage(len(m.Body))
```
and now I have 
```
2020/02/23 05:01:51 Ooops, message is nil!!!, now that's weird
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal 0xb code=0x0 addr=0x0 pc=0x0]
 
 goroutine 212 [running]:
 nanomsg.org/go/mangos/v2.(*Message).Dup(0x0, 0x100000000)
 	C:/Users/strow/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/message.go:161 +0x3
 nanomsg.org/go/mangos/v2/protocol/req.(*socket).send(0xc02e1e0)
 	C:/Users/strow/go/pkg/mod/nanomsg.org/go/mangos/v2@v2.0.8/protocol/req/req.go:89 +0x17
 nanomsg.org/go/mangos/v2/protocol/req.(*socket).AddPipe(0xc02e1e0, 0xa53e0, 0xc37dc80, 0x0, 0x0)

```
Now looking at 
https://github.com/nanomsg/mangos/blob/v2.0.8/protocol/req/req.go#L89

but I have no idea what's happening there.. Any particular reason, for `c.reqMsg` to be nil while redialing?

**Comment by strowk** [comment]
Ha, switch back to 2.0.5 actually helps (I'm sure, because bug is reproducing quite easily for me, I'm just restarting the server and redial in client always panics).
