### ISSUE TITLE
Problems integrating using CI pipeline

### ISSUE THREAD

**Issue by collincusce** [nanomsg/mangos#186]
Hey guys,

Great work, love the project, but when I try to install the application using our CI pipeline I run into a problem from my build script.  The build process pulls the code from our **private** repo and then uses `go get -t -v "./..."` to pull go dependencies. There are problems with pulling the code, though, and that causes an exit code of 1 to be generated in our build script. This fails the build entirely, and I don't want to special case skip that check for all go packages because if Mangos. I'm hoping you can advise.

The build script:

```sh
#!/bin/bash -e

# Ted: contact me when you make any changes

PREFIX="${PREFIX:-$(pwd)/build}"

SRC_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$SRC_DIR/env.sh"

GECKO_PKG=github.com/ava-labs/gecko
GECKO_PATH="$GOPATH/src/$GECKO_PKG"
if [[ -d "$GECKO_PATH/.git" ]]; then
    cd "$GECKO_PATH"
    go get -t -v "./..."
    cd -
else
    go get -t -v "$GECKO_PKG/..."
fi
go build -o "$PREFIX/ava" "$GECKO_PATH/main/"*.go
go build -o "$PREFIX/xputtest" "$GECKO_PATH/xputtest/"*.go
```
The package DOES pull down, but it also generates errors which results in an exit code being produced. On my local environment, running the build script once fails. Running it a second time passes because the library is pulled down already and no errors are generated.

The errors produced are as follows:

```sh
get "go.nanomsg.org/mangos": found meta tag get.metaImport{Prefix:"go.nanomsg.org/mangos", VCS:"git", RepoRoot:"https://github.com/nanomsg/mangos"} at //go.nanomsg.org/mangos?go-get=1
go.nanomsg.org/mangos (download)
package go.nanomsg.org/mangos/protocol/pub: unrecognized import path "go.nanomsg.org/mangos/protocol/pub" (parse https://go.nanomsg.org/mangos/protocol/pub?go-get=1: no go-import meta tags ())
package go.nanomsg.org/mangos/transport/ipc: unrecognized import path "go.nanomsg.org/mangos/transport/ipc" (parse https://go.nanomsg.org/mangos/transport/ipc?go-get=1: no go-import meta tags ())
```

Any suggestions?

**Comment by collincusce** [comment]
I think this will solve it: https://medium.com/@dayakar88/a-guide-to-solve-no-go-import-meta-tags-for-private-repositories-with-go-modules-6b9237f9c9f

**Comment by gdamore** [comment]
I think you're probably trying to import an older version of mangos.   The latest version of mangos is v3, with an import path like go.mangos.org/mangos/v3

(There is a v2 also, btw.)

This does require a modern go (v1.11 at least, and really I'd recommend 1.13 now -- 1.14 came out two days ago).  The reason is that you need a module aware go toolchain.  There were some bugs in the early module support around vanity imports.

Please try the latest version of mangos and let me know.

**Comment by collincusce** [comment]
I see sorry that was a message from one of my many experiments to fix the problem. This also occurs with the v3 version. My original imports were:

"go.nanomsg.org/mangos/v3"

"go.nanomsg.org/mangos/v3/protocol/pub"

//registers the IPC transport
_ "go.nanomsg.org/mangos/v3/transport/ipc"

Before I tried to fix the problem.

This is what I get when I put that back and run it:

```sh
get "go.nanomsg.org/mangos/v3": found meta tag get.metaImport{Prefix:"go.nanomsg.org/mangos", VCS:"git", RepoRoot:"https://github.com/nanomsg/mangos"} at //go.nanomsg.org/mangos/v3?go-get=1
get "go.nanomsg.org/mangos/v3": verifying non-authoritative meta tag
go.nanomsg.org/mangos (download)
package go.nanomsg.org/mangos/v3: cannot find package "go.nanomsg.org/mangos/v3" in any of:
	/home/ccusce/.gvm/gos/go1.13/src/go.nanomsg.org/mangos/v3 (from $GOROOT)
	/home/ccusce/.gvm/pkgsets/go1.13/global/src/go.nanomsg.org/mangos/v3 (from $GOPATH)
package go.nanomsg.org/mangos/v3/protocol/pub: unrecognized import path "go.nanomsg.org/mangos/v3/protocol/pub" (parse https://go.nanomsg.org/mangos/v3/protocol/pub?go-get=1: no go-import meta tags ())
package go.nanomsg.org/mangos/v3/transport/ipc: unrecognized import path "go.nanomsg.org/mangos/v3/transport/ipc" (parse https://go.nanomsg.org/mangos/v3/transport/ipc?go-get=1: no go-import meta tags ())
```

**Comment by gdamore** [comment]
Ah.... good old go get mode.  So I *think* that you have to use v2 for go get mode.  v3 is modules only.

Sorry for the mess here, but the go people really made life hell for existing projects when they introduced modules, and pretty much I cannot support both modules and legacy go get mode on the repo.  Its a mess.

To facilitate, there is a separate repo for mangos v2:

https://github.com/nanomsg/mangos2

Your import paths will be of the form:

"nanomsg.org/go/mangos/v2"

It's more or less impossible to support legacy go-get mode on the current repo.  I recommend moving towards modules at your earliest convenience.

**Comment by collincusce** [comment]
I dont think that's the problem. 

```sh
ccusce@AVAccusce:~/.gvm/pkgsets/go1.13/global/src/github.com/ava-labs/gecko$ go get -t -v "./..."
package go.nanomsg.org/mangos/v2: unrecognized import path "go.nanomsg.org/mangos/v2" (parse https://go.nanomsg.org/mangos/v2?go-get=1: no go-import meta tags ())
package go.nanomsg.org/mangos/v2/protocol/pub: unrecognized import path "go.nanomsg.org/mangos/v2/protocol/pub" (parse https://go.nanomsg.org/mangos/v2/protocol/pub?go-get=1: no go-import meta tags ())
package go.nanomsg.org/mangos/v2/transport/ipc: unrecognized import path "go.nanomsg.org/mangos/v2/transport/ipc" (parse https://go.nanomsg.org/mangos/v2/transport/ipc?go-get=1: no go-import meta tags ())
ccusce@AVAccusce:~/.gvm/pkgsets/go1.13/global/src/github.com/ava-labs/gecko$ 
```

I think the problem has something to do with the vanity url?  Did you check this article out?

https://medium.com/@dayakar88/a-guide-to-solve-no-go-import-meta-tags-for-private-repositories-with-go-modules-6b9237f9c9f

**Comment by gdamore** [comment]
Yes, the article has a very limited view of things, because it doesn't consider versioned APIs.

You're right that the vanity is playing a role.  I *do* have a vanity server up and running.

Your version 2 imports are wrong.    It's "nanomsg.org/go/mangos/v2"

Version 3 is quite different:  "go.nanomsg.org/mangos/v3"

**Comment by collincusce** [comment]
opps you answered as I deleted, I noticed the difference. I just changed v3->v2 instead of the entire URL from go.nano... to nanomsg.org/go/...

It *seems* to be working! I have to run some more tests now. Did the API change at all from v2->v3 or was it just added support for modules?

**Comment by gdamore** [comment]
It was just for modules.  There will be follow on changes but they will be 3.1, 3.2, etc.

**Comment by gdamore** [comment]
It's essentially impossible to support go get mode with versioned APIs using git branches.  The other choice would have been to copy the entire tree into a v2/ or v3/ subdir, but that way lies madness.

I've got so much fatigue from this whole thing that it's a mess.  Just switch to modules and move on -- definitely not going to be doing go get mode anywhere I don't have to.

**Comment by collincusce** [comment]
Hahah wellll it's going to be a hard sell getting the entire company to switch to go modules... especially this close to release. ;-) v2 is going to have to suffice for now. 

Thanks!

**Comment by gdamore** [comment]
I'm closing this for now.
