### ISSUE TITLE
Requests respond with send timeout after some time

### ISSUE THREAD

**Issue by rolandjitsu** [nanomsg/mangos#201]
I've noticed some odd behaviour while using mangos to make requests (using the req/rep protocol) from a mangos client to a nng server.

I have a nng server that runs indefinitely and responds to requests from a mangos client that also runs indefinitely (both are systemd services) I'm using the IPC transport and I use the same socket  (I create the socket once and dial, then I open new contexts for each request) to make the requests.

I created a small wrapper around mangos:
```go
package nng

import (
    "crypto/tls"
    "fmt"
    "time"

    "go.nanomsg.org/mangos/v3"
    "go.nanomsg.org/mangos/v3/protocol/req"
)

type SocketParams struct {
	Addr       string
}

func NewRequestSocket(params SocketParams) RequestSocket {
	return &socket{SocketParams: params}
}

type RequestSocket interface {
	Open() error
	Close() error
	Request([]byte) ([]byte, error)
}

type socket struct {
	SocketParams
	sock mangos.Socket
	d    mangos.Dialer
}

func (s *socket) Open() (err error) {
	s.sock, err = req.NewSocket()
	if err != nil {
		return
	}

	opts := map[string]interface{}{}
	s.d, err = s.sock.NewDialer(s.Addr, opts)
	if err != nil {
		return
	}

	err = s.d.Dial()

	return
}

func (s *socket) Close() error {
	return s.sock.Close()
}

func (s *socket) Request(msg []byte) (res []byte, err error) {
	var ctx mangos.Context

	ctx, err = s.sock.OpenContext()
	if err != nil {
		return
	}
        defer ctx.Close()

	err = ctx.Send(msg)
	if err != nil {
		return
	}

	res, err = ctx.Recv()

	return
}
```
```go
package main

...

func main() int {
    s := NewRequestSocket(SocketParams{
    	    Addr: "ipc:///tmp/test-sock.ipc",
    })

    err := s.Open()
    if err != nil {
        return -1;
    }
    
    defer s.Close()
    
    msgs := []string{"a", "b", "c"}
    for {
        time.Sleep(100 * time.Millisecond)
        for msg := range msgs {
            go func(msg string){
                rep, err := s.Request([]byte(msg))
                if err != nil {
                    fmt.Println(err)
                } else {
                    fmt.Println(string(rep))
                }
            }(msg)
        }
    }
```

On the server side, I use a similar server impl. to the [async server example](https://github.com/nanomsg/nng/blob/master/demo/async/server.c).

It takes about 30 - 45 mins or so (I've seen longer periods) until the requests start failing with the `ErrSendTimeout` error.

How would I go about debugging this issue - is there a way to get notified if the socket from the mangos side died? Any clue what may be going on?

### UPDATE 08.06.2020
I've added a pipe hook to check when a connect/disconnect happens:
```go
...

func (s *socket) Open() (err error) {
    ...
    s.sock.SetPipeEventHook(func(evt mangos.PipeEvent, p mangos.Pipe) {
        if evt == mangos.PipeEventAttached {
            fmt.Printf("PIPE %d CONNECTED\n", p.ID())
        } else if evt == mangos.PipeEventDetached {
            fmt.Printf("PIPE %d DISCONNECTED\n", p.ID())
        }
    })
    ...
}
```

And I only see a `CONNECTED`, so I assume there's no disconnect.

**Comment by nyobe** [comment]
I've noticed this as well. After _closing_ a `req` context, sometimes the pipe won't be re-added to the socket ready queue, which leaves the socket in an inoperable state. All subsequent sends will time out until something causes a new pipe to be attached.

I believe what's happening is that [sendCtx](https://github.com/nanomsg/mangos/blob/master/protocol/req/req.go#L115) is getting unlucky and not acquiring the socket mutex to re-add its pipe to the ready queue until _after_ the context gets closed, which causes the pipe to get dropped.  It's possible for it to be blocked while the subsequent receive and close acquire the mutex before it.

A possible fix might be for it to always add its pipe back to the ready queue (if it isn't closed), regardless of whether the context was closed:
```
- if !c.closed && !p.closed {
+ if !p.closed {
```
