### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by gmonk** [nanomsg/mangos#203]
examples complain about go.nanomsg.org/mangos/v3   will only work if changed to go.nanomsg.org/mangos
Description shows changing imports to include v3  is this not correct ?

**Comment by gdamore** [comment]
You need to use modules... Or else use mangos v2 instead of v3.

**Comment by gdamore** [comment]
We should fix the examples I suppose.

**Comment by gdamore** [comment]
So all the examples are using v3.  I think this is probably the result of using a too old version of go.   Or possibly trying to use gopath mode -- I'm not sure gopath mode works properly with mangos v3 -- it *should* - but you'll need to use a relatively modern Go (nothing older than go 1.10 for certain.)
