### ISSUE TITLE
Consider vendoring gorilla websocket

### ISSUE THREAD

**Issue by gdamore** [nanomsg/mangos#211]
The gorilla packages have broken several times recently.  This badly impacts our own software, and our downstreams.  We need to look at ways to insulate ourselves from upstream breakage.

**Comment by dangerousHobo** [comment]
I'd assume you would take the [typical Go approach](https://blog.gopheracademy.com/advent-2015/vendor-folder/) and create a `vendor` directory and place the gorilla packages inside. The question is, which commit/release to vendor?
For months I've been using commit C45A6353 (March 2), without issue. I've recently updated to the latest (A69D25BE Aug 2), but haven't does sufficient testing yet.

**Comment by binary132** [comment]
Vendoring should be managed by the package user (i.e. the application), not the package maintainer.  That said, perhaps a govendor `vendor.json` could be provided?  I wonder if there's a utility waiting to be made for merging an imported package's depfile into an application's depfile / detecting conflicts.

**Comment by gdamore** [comment]
We may decide to redesign this not to use gorilla websocket -- the main websocket package has had changes which address the main concern, which was that we needed a way to limit the size of websocket requests.

**Comment by gdamore** [comment]
The pkg/x/net standard WebSocket just isn't up to the task.  It doesn't preserve message boundaries, and it seems to be somewhat unmaintained.  So we will stick with gorilla.

**Comment by gdamore** [comment]
So vendoring isn't the answer.  Maybe post go1.11 creating a module would be appropriate.

For now I'm closing this.  Revisit this when modules are part of the standard go ecosystem.
