### ISSUE TITLE
go get -v go.nanomsg.org/mangos/v3 fails

### ISSUE THREAD

**Issue by vinjvinj** [nanomsg/mangos#220]
go get -v go.nanomsg.org/mangos/v3

get “go.nanomsg.org/mangos/v3”: found meta tag get.metaImport{Prefix:“go.nanomsg.org/mangos”, VCS:“git”, RepoRoot:“https://github.com/nanomsg/mangos”} at //go.nanomsg.org/mangos/v3?go-get=1
get “go.nanomsg.org/mangos/v3”: verifying non-authoritative meta tag
go.nanomsg.org/mangos (download)
cannot find package “go.nanomsg.org/mangos/v3” in any of:
	/usr/local/Cellar/go/1.15.5/libexec/src/go.nanomsg.org/mangos/v3 (from $GOROOT)
	/Users/<username>/test/sv/src/modulesgo/src/go.nanomsg.org/mangos/v3 (from $GOPATH)

**Comment by gdamore** [comment]
If you're using mangos v3 then you need to be using go modules.

If you're not using go modules, then use mangos v2, which has a totally different import URL.

**Comment by gdamore** [comment]
(Basically, modules and vanity naming, and semantic versioning can't be made to work equally well with both old GOPATH mode and go modules mode... because of defects in the tooling.)

**Comment by vinjvinj** [comment]
Thanks for the quick reply. It works fine for me on Linux but fails on Mac. Let me try with go modules and see if it works.

**Comment by gdamore** [comment]
Can I close this?

**Comment by vinjvinj** [comment]
I could not get it to work. I need to spend more time debugging
understanding how to move my existing large code base to go modules

**Comment by vinjvinj** [comment]
I was able to migrate to go modules. I'm still getting the error:

message/messagebus/socket.go:21:8: socket.AddTransport undefined (type
mangos.Socket has no field or method AddTransport)
message/messagebus/socket.go:21:22: undefined: ipc.NewTransport
message/messagebus/socket.go:22:8: socket.AddTransport undefined (type
mangos.Socket has no field or method AddTransport)
message/messagebus/socket.go:22:22: undefined: tcp.NewTransport
message/messagebus/socket.go:32:8: socket.AddTransport undefined (type
mangos.Socket has no field or method AddTransport)
message/messagebus/socket.go:32:22: undefined: ipc.NewTransport
message/messagebus/socket.go:33:8: socket.AddTransport undefined (type
mangos.Socket has no field or method AddTransport)
message/messagebus/socket.go:33:22: undefined: tcp.NewTransport

I had the following code:

 socket.AddTransport(ipc.NewTransport())
socket.AddTransport(tcp.NewTransport())

I see your comment:

"For most stock transports, it should be sufficient for an application to
import the package (with a "_" import) to register the transport"

So just doing this should be sufficient?

 _ "go.nanomsg.org/mangos/v3/transport/ipc"
_ "go.nanomsg.org/mangos/v3/transport/tcp"

**Comment by gdamore** [comment]
Yes, that should be sufficient.
