### ISSUE TITLE
Asynchronous client/server pattern ?

### ISSUE THREAD

**Issue by Bai-Yingjie** [nanomsg/mangos#223]
Mangos is a great project! With the purpose looking for a pure go implementation of ZMQ, I am so lucky that I came here~

I wanted to convert my little client/server tool to mangos based implementation, where the clients send some ID info to the server to initiate a session, and server replies with the session info upon it is created, after the session info are received by clients, they can start sending some periodic statistic data(like CPU usage of that client); for server side, after the session is established, the server just receives data from corresponding client and does not reply.

I find ZMQ's DEALER/ROUTER pattern can do this in a generic asynchronous client/server way:
* Clients connect to the server and send requests.
* For each request, the server sends 0 or more replies.
* Clients can send multiple requests without waiting for a reply.
* Servers can send multiple replies without waiting for new requests.

But in mangos I cannot find this pattern, am I missing something?

**Comment by gdamore** [comment]
The last thing is where it fails.  You don't have any state machine that fits the traditional REQ/REP, PUB/SUB, or even SURVEYOR patterns.

You thus will need to use PAIR or BUS protocol -- either of which can do this.  You'll have to write any stateful handling (such as request retries or whatever) yourself -- mangos will only be managing the connections, and message delimiting, the rest of the details will be up to you.
