### ISSUE TITLE
Implement io.Reader and io.Writer

### ISSUE THREAD

**Issue by munnik** [nanomsg/mangos#226]
I'm not sure if there is a specific reason why these interfaces are not implemented. I would expect that 
a Mangos socket would implement https://golang.org/pkg/io/#Reader and https://golang.org/pkg/io/#Writer.

I think it should be easy enough to write wrappers around `nc (s *socket) Recv() ([]byte, error) {}` and  `func (s *socket) Send(b []byte) error {}` that implement these interfaces. If there are no specific reasons why this has not been done I will try to write them and make a PR.

This would help me with writing test, I can then just replace the `mangos.Socket` with a `bytes.Buffer` and check if data is actually send/written in my function.

**Comment by gdamore** [comment]
(You could build a wrapper if you're using mangos as a transport for stream data.  That would be atypical usage, however, and I don't want to encourage it directly since it will lead to many questions.  But if you need it *and* you're just interested in using mangos to transport byte streams rather than messages, then you can certainly do it.

**Comment by gdamore** [comment]
However, it could only reasonably work with a small subset of the protocols -- pipeline (push/pull), and pair probably.  I think all the others would be doomed to failure.

**Comment by gdamore** [comment]
For example, you can only *send* a reply on a REP socket after first receiving a *message*.  If you receive part of a message, or receive two messages, it breaks the state machine that is the point of mangos.

**Comment by munnik** [comment]
Ok, that's a good reason ;-) I will then implement a the mangos.Socket interface in my tests. Maybe having a mangos.SocketReceiver and mangos.SocketSender interface is then a good idea. Now I have to implement quite some functions

**Comment by munnik** [comment]
I use mangos for a pipeline so did not really think of any other scenarios.

**Comment by gdamore** [comment]
I think even with a pipeline it might be a mistake -- because if you have multiple peers you will wind up breaking the streams up at arbitrary places, intermixing them.  For a 1:1 connection it would be fine but as soon as a socket can have more than one peer you don't want to do this.
