### ISSUE TITLE
Push with subscriptions

### ISSUE THREAD

**Issue by istalker2** [nanomsg/mangos#227]
Hello!

There is pub/sub pattern where one can provide a subscription and get all the messages matching the subscription, but the message is broadcasted to all subscribers. There is also pull/push that does load-balancing, but does not have subscriptions. How do I combine both patterns?

In my case I have a single work distributor and N workers, but workers are not equal. Some can handle tasks of category A, some other can only handle category B etc. I need to push task X to just one agent, but that agent can only be one of those subscribed to X. Also, that's a star topology where all agents connect to a single distributor and pull tasks from it. 

One way of doing it could be to have 1 push socket per each task category and make each worker connect to the socket of its category. But then I'll need to have exposed TCP port per each task category which won't work for me (I can only open small number of well known ingresses). 

Thank you!

**Comment by istalker2** [comment]
With survey, if I understand it correctly, all workers will receive the task. What I'm looking for is a round-robin delivery, but with additional control over which pipes are suitable for the message. 

I.e. pipes are filtered out by the subscription (like SUB works, but the filtration takes place on the publisher side), then the message is delivered to the first pipe in the filtered list and then the pipe moves to the end of the list.

By looking at the protocols code, it seems that I'll be able to write a protocol that does that for my task, but I don't know how good of idea it is. I was hoping that this could be achieved by building on top of existing patterns as the task seems generic enough. Basically it's the same push/pull just not all workers are interchangeable.

**Comment by gdamore** [comment]
Yeah, I think you'll need to build a custom pattern for this -- you could probably build a something using multiple patterns, but nothing right now is builtin that offers what you want.

**Comment by gdamore** [comment]
Going back and thinking about this, I think you can probably consider using websockets.  This will allow you to use multiple separate mangos "sockets", but still only use a single TCP port.  The discrimination will be done with web socket URLs (the path component.)

I don't know why that didn't occur to me earlier.  But this is what I recommend you do for now.

In the meantime I'm closing this ticket.
