### ISSUE TITLE
graceful upgrades

### ISSUE THREAD

**Issue by amery** [nanomsg/mangos#236]
hi, I use tableflip for graceful upgrades. is it possible to pass a pre-allocated listener to mangos?

**Comment by gdamore** [comment]
Not at this time.  However with normal SP protocols you should really need to worry about this ... although you need to listen "asynchronously" and your dialers need to dial asynchronously -- which are all just flags to the API -- in order that they self heal.  Then start the new process (which won't be able to bind yet, but will keep retrying), and then kill the old one.  There will be a tiny window where TCP connections will be refused, but the mangos client gracefully handles that with automatic retries.

**Comment by amery** [comment]
thank you, I'll do it that way
