### ISSUE TITLE
How to connect zeroMQ client to server behind ELB/docker

### ISSUE THREAD

**Issue by subbu05** [nanomsg/mangos#247]
Hi,

I am looking for some suggestions to connect 0MQ client to 0MQ server behind ELB/Proxy.

I have a client and server code as containers and not able to connect with docker.
Same issue with connecting via ELB. 

Any suggestions?

**Comment by gdamore** [comment]
0mq is not us. Mangos and Nanomsg and NNG all use SP protocols which are a totally different protocol family from 0mq. Sorry.

**Comment by subbu05** [comment]
I mean using mango client and server I was unable to connect via ELB/docker. Any help appreciated.
I get error EOF while trying to connect.

**Comment by gdamore** [comment]
Do you have some sample code?  I'm not familiar with ELB.  I assume it's just TCP with a DNS round robin or something like that?

**Comment by gdamore** [comment]
EOF is a strange error.  It probably means one side disconnected.  Are you sure you're using a dedicated port for this?  Again sample code demonstrating the problem would make it easier to assist you.

**Comment by subbu05** [comment]
I added sample code here https://github.com/subbu05/sample-0mq
Steps
1.  Ensure docker engine is running
2. Run build.sh
3. run  server `docker run -d --name server -p 10000:10000 sample` 
4. run client `docker run -it --name client  sample  /sample node1 tcp://<docker-host-IP>:10000`

Observe that you will see following error
_start client
can't dial on req socket: EOF_

**Comment by subbu05** [comment]
curl shows connected (to test reachability)
`curl -v http://10.0.0.48:10000 
*   Trying 10.0.0.48:10000...
* Connected to 10.0.0.48 (10.0.0.48) port 10000 (#0)
> GET / HTTP/1.1
> Host: 10.0.0.48:10000
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 10.0.0.48 left intact
curl: (52) Empty reply from server
`

**Comment by gdamore** [comment]
It looks to me like some kind of HTTP is stuck in the middle.  Mangos will only use HTTP if you use the websocket transport.

My guess is that the load balancer you are using is only intended for web applications. Mangos and nanomsg have their own protocols.

You can try websocket but I suspect that you will need to arrange to make the proxy in the middle pass the correct headers for our websocket negotiation.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by subbu05** [comment]
There is no HTTP used for REQ/REP. Here in docker the network is tcp based which should work when port based forwarding happens. 

If I use websocket I add more overhead in using http for data. My idea is to use minimal protocol to ship data from client to server hence I selected mangos.

**Comment by subbu05** [comment]
I tried with "github.com/go-zeromq/zmq4" library and was able to connect via Docker. I will go ahead and use this instead mangos. Also let me debug where the issue is happening with mangos when connecting via docker or ELB. This can be major issue if users plan to use docker containers/K8s/ELB.

**Comment by gdamore** [comment]
CLosed since we don't have enough info to debug it (I don't think it's a software bug.)
