### ISSUE TITLE
Is there any example for req/rep protocol using IPC as transport?

### ISSUE THREAD

**Issue by vikaspushkar** [nanomsg/mangos#260]
I am trying to use req, rep protocol using IPC as transport. is there any example for the same? also, does IPC transport supports the darwin platform as well? I could not see any _darwin.go under IPC transport hence asking this question.

**Comment by gdamore** [comment]
I didn't create a dedicated req/rep example.  It works like tcp except you specify a URL differently.  For example ipc:///var/run/example.socket

It gets wonky if you try to use abstract sockets but if you don't know about them then I recommend sticking with vanilla ones. Abstract sockets are only supported on Linux anyway.

**Comment by vikaspushkar** [comment]
thanks this is helpful.
