### ISSUE TITLE
why following code using mangos creates 2 instances of pipe

### ISSUE THREAD

**Issue by vikaspushkar** [nanomsg/mangos#263]
this is my code using mangos to create a pipe socket and listen on it for windows.

```
 url="ipc:///tmp/manew_pipe"
func listenIPC(url string) (mangos.Socket, error) {
	var sock mangos.Socket
	var err error
	fmt.Println("Create new Socket")
	if sock, err = rep.NewSocket(); err != nil {
		fmt.Println(" could not create new Socket")
		return sock, fmt.Errorf("could not open IPC socket to listen %s", err.Error())
	}
	if err = sock.Listen(url); err != nil {
		fmt.Println("could not listen on IPC socket ", err.Error())
		return sock, fmt.Errorf("could not listen on IPC socket %s", err.Error())
	}
	return sock, nil
}
```
when i see pipe using "get-childitem \\.pipe\ -filter "*tmp*"

it shows 

```
Directory: \\.\pipe\tmp

Mode                 LastWriteTime            Length     Name
-------               ---------------           -------- -------
---------            some date-time         2          tmp\manew_pipe
```

ideally, the length should be 2 since there is no client that has dialed to this pipe, also when a client dials to this listener the length becomes 3( ideally it should be 2). sometimes the client cannot dial the pipe and gets stuck. 
What possibly could be going wrong here.      
here the dialing client is using actual nng lib.

When starting a listener on the pipe using c++ nng lib, it only creates a listener of 1 length.

**Comment by gdamore** [comment]
On windows, IPC and named pipes work differently than on UNIX, but we want to provide something like the same UNIX domain socket semantics.

To do this we always create an extra pipe, so we have one ready to go to replace the one we're going to transform into connected pipe.

(In UNIX, accept() creates a new pipe for the connecting process... in Windows it simply transforms the existing pipe.)

This code ensures that a client program never sees "ECONNREFUSED" if another client is connecting at the same time.
