### ISSUE TITLE
Req Protocol Dial gives unsupported transport error

### ISSUE THREAD

**Issue by donmezburak** [nanomsg/mangos#269]
Hello,

I can create socket but Req protocol dial gives error. 

MacOS M1 pro Monterey.
Code:

`"go.nanomsg.org/mangos/v3"
	nanoReq "go.nanomsg.org/mangos/v3/protocol/req"
if reqSock, err = nanoReq.NewSocket(); err != nil {
		log.WithFields(log.Fields{
			"type":     "err_socket_new",
			"zmq_spec": spec,
			"err":      err,
		}).Info("Socket new error")
		return nil, 1, nil
	}

	if err = reqSock.Dial(spec); err != nil {
		log.WithFields(log.Fields{
			"type": "err_socket_dial",
			"spec": spec,
			"err":  err,
		}).Info("Socket dial error")`

Error:

level=info msg="Socket dial error" err="invalid or unsupported transport" spec="tcp://127.0.0.1:11123" type=err_socket_dial

Thanks

**Comment by donmezburak** [comment]
I solved the problem.

Problem was due to tcp init is not called before the dial. So transport returns null. So that, I added `tcp "go.nanomsg.org/mangos/v3/transport/tcp"` and called a dummy line `tcp.Transport.Scheme()`. Transport is added to list and returned.

**Comment by gdamore** [comment]
It should be possible to just import the transport (use _ to import without having to explicitly call anything).  The transport registers itself as part of it's init().
