### ISSUE TITLE
QUIC Protocol for remote stuff

### ISSUE THREAD

**Issue by lonnietc** [nanomsg/mangos#271]
Hello,

I have just come across Mangos (pure Go) and am interested in possibly using it for a type of P2P application.

Was wondering if it has QUIC protocol availability since that it apparently the fastest, open sourced, protocol that seems to be available.

Any ideas or suggestions would be greatly appreciated.
Thanks in advance

**Comment by gdamore** [comment]
I have not implemented a QUIC transport.  It would probably be easy to do for mangos, but it's a substantially larger effort if you want to support interop with NNG or nanommsg.

**Comment by gdamore** [comment]
The request for this is tracked in #40
