### ISSUE TITLE
Transport: Add serial transport

### ISSUE THREAD

**Issue by piyongcai** [nanomsg/mangos#272]
hi, Have any plans to add serial port transport？

**Comment by gdamore** [comment]
I didn't have any such plans.  It would be easy to do though, given a use case for it.  Both parties would need to agree about the serial comms, and usually the set up for such things is a bit ... dodgy during early start up.  Any reason not to just run SLIP or PPP over the port?

**Comment by gdamore** [comment]
So we've been discussing some ideas, and I think the idea of a "file descriptor" transport would serve this need -- you set up the serial port as you want, then hand the file descriptor over to mangos.

**Comment by gdamore** [comment]
Closing this in favor of #290  -- I'm not going to do anything "special" for serial ports here.
