### ISSUE TITLE
nanomsg port

### ISSUE THREAD

**Issue by kehiy** [nanomsg/mangos#279]
we have a nanomsg server in our Golang project, and we are thinking to choose a new port for this server.
is there any default port for nanomsg?

**Comment by kehiy** [comment]
@gdamore

**Comment by gdamore** [comment]
No default port -- each application is unique, and should choose it's own.  You need different ports for different messaging patterns (PUB/SUB vs. REQ/REQ, etc.) and frequently each application will also need it's own port (not each *process*, but each major application, although you can break that down with routing if you need to conserve ports.)

**Comment by gdamore** [comment]
If you really have a constraint about port numbers, then I recommend using websocket. :-)  Then you use just a single TCP port, and can discriminate different applications/usages based on the URL.
