### ISSUE TITLE
Device() should return a handle

### ISSUE THREAD

**Issue by linuxerwang** [nanomsg/mangos#29]
At present there is no way to detect or be notified if a device broke, and there is no way to terminate a device.

nanomsg does it through nn_device/nn_term.

**Comment by gdamore** [comment]
You can close the underlying socket (either socket), which will do the trick.

nn_term shutdown the whole library in nanomsg, you don't want that in mangos.  In either mangos or NNG, just close one of the two sockets you used to make the device (doesn't matter which), and it will shut down gracefully.

**Comment by gdamore** [comment]
As there is no work to do this -- it already works, closing.
