### ISSUE TITLE
Support Golang 1.22

### ISSUE THREAD

**Issue by kevdowney** [nanomsg/mangos#299]
Upgrade golang library to latest [Golang 1.22](https://tip.golang.org/doc/go1.22)

The current go version is out of support (1.13):
https://github.com/nanomsg/mangos/blob/59783632613ad0d8d1ec05dc70cbfc8bcf9c0ad4/go.mod#L9

**Comment by gdamore** [comment]
So that go.mod means it is the *minimum* version of go that we can support.  It doesn't mean you can't upgrade to a newer version.
