### ISSUE TITLE
Enhancement:  Add QUIC transport

### ISSUE THREAD

**Issue by lthibault** [nanomsg/mangos#308]
Hi @gdamore,

As per our earlier conversation on gitter, I am hereby submitting an RFE to include https://github.com/lthibault/quic-mangos as a transport in mangos.

As a reminder, external dependencies are:

- https://github.com/SentimensRG/ctx (utilities around contexts;  small library also authored by me, which needs some love)
- https://github.com/lucas-clemente/quic-go (QUIC implementation in pure go)

If, for whatever reason, we determine that quic-go should not be included, I'm hoping you might consider linking to it from the README, as it would be much appreciated.

Best,
Louis

**Comment by lthibault** [comment]
@gdamore Have you had a chance to consider this RFE?  Anything I can do on my end?

**Comment by gdamore** [comment]
Sorry, I've been busy.  I hope to get to it soon. :-)

**Comment by gdamore** [comment]
I'll be working on this soon, but first I'll like to your experimental transport.  One thing we need to do is get an RFC written for this. :-)

**Comment by gdamore** [comment]
@lthibault I've been going through your code, and trying to understand both QUIC and your details.  A few things are definitely missing, and an RFC seems to be pretty important as QUIC has the stream multiplexing capability.  You're using a path to identify different streams I think, but I'm right now trying to figure out how a client turns that URL into a destination.

The other stuff missing relates to handling of certificates, which seems to be really important with QUIC, and perhaps other TLS stuff.

**Comment by lthibault** [comment]
@gdamore Re the TLS/QUIC configuration, that ought to be covered by https://github.com/lthibault/quic-mangos/issues/3, which will allow users to pass in instances of `*tls.Config` and `*quic.Config`.

Concerning the RFC, I've never had to write one before.  I'm happy to give it a whirl, but could definitely use some guidance. Do you have an example I could work from, or something to point me in the right direction?

**Comment by gdamore** [comment]
Please have a look at the documents in https://github.com/nanomsg/rfcs - there are samples you can start from.  Probably you should start from the TLS RFC as a base.

**Comment by lthibault** [comment]
Will do, thanks.

**Comment by nri-pl** [comment]
Hi, any progress?

After the release of version 1.4
```
cannot use quic.NewTransport() (type "github.com/go-mangos/mangos".Transport) as type "nanomsg.org/go-mangos".Transport in argument to sock.AddTransport:
	"github.com/go-mangos/mangos".Transport does not implement "nanomsg.org/go-mangos".Transport (wrong type for NewDialer method)
		have NewDialer(string, "github.com/go-mangos/mangos".Socket) ("github.com/go-mangos/mangos".PipeDialer, error)
		want NewDialer(string, "nanomsg.org/go-mangos".Socket) ("nanomsg.org/go-mangos".PipeDialer, error)
```

**Comment by lthibault** [comment]
@nri-pl ,  I unfortunately have not had time to dig into this.  I'd very much welcome a PR, however.

**Comment by gdamore** [comment]
This is just a need to update import paths. Sorry for the confusion.

**Comment by lthibault** [comment]
@nri-pl Import paths have been fixed.  Should be working now.

**Comment by gdamore** [comment]
I'm deferring integrating this into mangos until v2.  I am cleaning up the transport provider API in mangos v2, and then we'll do this properly.

**Comment by gdamore** [comment]
Note that current work on mangos v2 is at github.com/nanomsg/mangos-v2 -- still experimental of course.

**Comment by lthibault** [comment]
Understood — sounds good to me.

**Comment by gdamore** [comment]
Closing this here, we have the issue in mangos v2, and the link back.

Note that mangos v2 may still have some underpinning transport changes.  I don't really consider the underlying Transport API part of my committed interface *yet*.  That will change soon.
