### ISSUE TITLE
Wrong go get reference

### ISSUE THREAD

**Issue by delioda79** [nanomsg/mangos#328]
The readme currently states:
go get -u github.com/nanomsg/go-mangos

this is now wrong as teh repository is nanomsg/mangos

**Comment by sbinet** [comment]
actually, this should probably be:
```
$> go get nanomsg.org/go-mangos
```

**Comment by delioda79** [comment]
Oh yes, I was getting mad also as I had put github.com/nanomsg/mangos inside my import.....thought that was the right one
