### ISSUE TITLE
Export protocol structs to facilitate extension

### ISSUE THREAD

**Issue by lthibault** [nanomsg/mangos#330]
I often find myself wanting to extend existing protocols by adding a `ProtocolSendHook` or `ProtocolReceiveHook`.  At present, this is achieved in the following (very convoluted) way:

```go 
type myproto struct { mangos.Protocol }

func (myproto) SendHook(m *Message) bool {
    // custom logic goes here
}

sock, _ = star.NewSocket()
sock = mangos.MakeSocket(&myproto{sock.GetProtocol()})

// use sock as usual...
```

This would be much facilitated by either:
- adding a `func NewProtocol() mangos.Protocol` function in each protocol subpackage.
- exporting the concrete protocol struct in each protocol subpackage

@gdamore, if this seems okay to you, I'd be happy to do the PR myself.

**Comment by gdamore** [comment]
I have mixed feelings.  On the pragmatic side, I understand wanting these concrete structures.  But the other side of this is that by not exposing them, I minimize the size of the promise I'm making with the API -- and I expect to want to change some of these details in the future.  By not exposing stuff that is not intentionally part of the API, I leave myself freedom to make changes without worrying about breaking stuff.

Any chance you can describe your protocol changes in more detail?  Maybe it would be best to just upstream them?

**Comment by lthibault** [comment]
>by not exposing them, I minimize the size of the promise I'm making with the API

That makes sense, which is why I personally like the first option, namely adding e.g. `pair.NewProtocol()`, which would return a `mangos.Protocol` interface.  Since `mangos.Protocol` is already part of the public API, the change seems minimal.

>Any chance you can describe your protocol changes in more detail?

I've had to do this a few times, and each time has been something very project-specific (e.g.: inspecting the payload to drop certain messages).

**Comment by gdamore** [comment]
Ok, given this, it seems like your suggestion has merit.  Go ahead and drop me a PR.   It may take a bit for me to get to it -- I'm traveling a bit this week.

**Comment by gdamore** [comment]
Closed in #331

**Comment by gdamore** [comment]
Well, I have some bad news.

The Protocol API is completely changing soon.  I really should never have made that API *public*.

The changes in my context tree structure will break your code if you relying on this.   But the benefits of rewhacking the Protocol to behave differently so that I can separate Protocol state from the socket to allow creation of something I'm calling "ProtocolContext" far outweigh (IMO) the downsides of breaking this API.

**Comment by gdamore** [comment]
These breaking changes will be in the mangos 2.0 work... the 1.x tree (from v1 tag) will of course be unaffected.

**Comment by lthibault** [comment]
Fair enough.  Thanks for the heads-up, and looking forward to v2.
