### ISSUE TITLE
Dial timeout?

### ISSUE THREAD

**Issue by richrarobi** [nanomsg/mangos#337]
Would it be possible to have an example that shows how to implement Dial options (particularly for Request side of req/rep) - If a server doesn't respond to Dial I would like to timeout more quickly. (Multiple servers)
    sock.AddTransport(tcp.NewTransport())
// these seem to have no effect
//    err = sock.SetOption(mangos.OptionBestEffort, true)
//    err = sock.SetOption(mangos.OptionRetryTime, 0)
    if err = sock.Dial(url); err != nil {
          return "Cannot Dial"
        }

**Comment by gdamore** [comment]
What you want is OptionReconnectTime and OptionMaxReconnectTime.

(The first sets the minimum time between redial attempts. If the second is not zero, then the time is doubled between successive failures, until maxing out at the specific maximum time, acting as an exponential backoff.)

  - Garrett

**Comment by gdamore** [comment]
I think I answered the question.  I'm going to close this for now.  Feel free to continue the thread here if necessary, as I do monitor even closed bugs.

**Comment by richrarobi** [comment]
Those settings didn't appear to change the dial timeout. However, I realised that I should have put each call to different servers in their own go routine. This has the effect that it doesn't matter about the length of the dial timeout. The other servers now continue as normal without the one that is not running.
Thanks for answering, tho'.

**Comment by gdamore** [comment]
Ok, cool.  Yeah, timing out the initial Dial() is something that isn't done, and is highly transport specific (e.g. you have to set some TCP options for changing how long connect() etc. takes.)  Right now mangos and nanomsg and NNG all just assume that the underlying transport has sensible timeouts.
