### ISSUE TITLE
Want pairv1

### ISSUE THREAD

**Issue by gdamore** [nanomsg/mangos#71]
In https://github.com/nanomsg/nng - we have a new PAIRv1 protocol, which adds better resilience for loops in device plumbing.

We should go ahead and add that.  We might also use this opportunity to try to support polyamorous mode from nng in our new v1 pipes.

**Comment by gdamore** [comment]
I'm probably not going to do this.  I've been thinking a lot about PAIRv2 (and polyamorous mode in particular), and its fairly completely busted as it won't work across devices.

I'm in the design phases for a new Mesh protocol, which should work better, but will require protocol participants to take a bigger role in keeping state.  But it should permit consumers to to play more too.

This may need a new API, sort of a SendTo() where we can supply a destination node ID.  Really this is probably going to need significant changes to the wire protocols, which is why it needs to be a new thing.

**Comment by ngjaying** [comment]
Hi @gdamore, are there any progress about this? We would like to communicate with nng pair1 from golang as the client, is it possible to do that?

**Comment by gdamore** [comment]
If you have a need I can probably knock this out in an hour or so.  I just hadn’t gotten around to it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ngjaying** [comment]
We do have a need. We try to adopt nng protocol for inter process communication. The c implementation and python wrapper  support pariv1, but unfortunately, the go support is missing. I think one of the common scenario of using nng is to communicate across different languages. This inconsistency may be an obstacle to adopt this protocol for many potential users. I think it is very valuable and worthy to spare several hours to complete this. Thanks in advance.

**Comment by gdamore** [comment]
I am nearly done with it -- spent some time tonight on it... about 90 minutes of coding, but the main bit I still have to do is the self test.  Stay tuned.  Soon.

**Comment by gdamore** [comment]
Btw, I'm only implementing the monogamous mode in mangos.  Polyamorous mode is deprecated (although I don't have a replacement for it yet), and a lot more complex to get right.  (Impossible to get "right" actually, which is why it is deprecated.)

**Comment by ngjaying** [comment]
Fantastic, really appreciate it

**Comment by gdamore** [comment]
Please see PR #253 -- if you can check that out in a branch and confirm it works for you that would be very helpful!  When I merge this I will bump the minor version number for this repo.

**Comment by ngjaying** [comment]
Thanks @gdamore This PR works like a charm in our initial scenario.
