### ISSUE TITLE
Dial with v2 only works if receiver is up

### ISSUE THREAD

**Issue by jhawk28** [nanomsg/mangos#87]
Dial fails with "connection refused" if the listen side is started afterwards.

```
cd examples/pipeline
go run pipeline.go node1 tcp://127.0.0.1:8085 hi
```

**Comment by gdamore** [comment]
Yes, that's right.  Possibly the examples need to be updated.  This is an optional behavior, and we changed the default in mangos v2 to require that the server be up -- this is a little less self healing, but its more diagnosable than just spinning forever in the background if you gave the wrong URL for example.

You can change this default behavior with the OptionDialAsynch socket option.

**Comment by gdamore** [comment]
Actually the example shell script does start the server first.
