### ISSUE TITLE
pubsub using ipc fails after first run

### ISSUE THREAD

**Issue by jagorski2** [nanomsg/mangos#88]
`./run.sh 
can't listen on pub socket: listen unix test.ipc: bind: address already in use
can't dial on sub socket: dial unix test.ipc: connect: connection refused
can't dial on sub socket: dial unix test.ipc: connect: connection refused
can't dial on sub socket: dial unix test.ipc: connect: connection refused
`
Changed the url in the run.sh script to be ipc://test.ipc.

Get the above error message on the iterations after the first run. Is there additional cleanup that should be done when using ipc in a real application? I see the test.ipc file is still there after all the programs exit.

**Comment by gdamore** [comment]
Probably we need to delete the IPC file when the server exits.  I do this in the C code, but I'm not sure we are doing this in mangos.

**Comment by gdamore** [comment]
So if the listener is gracefully shut down, then Go automatically cleans up the socket.  I think we're not doing this cleanly and that's the problem.

**Comment by gdamore** [comment]
Yes, that's precisely the problem with the demo.  But it is after all a demo.  If you want to use IPC, you should probably shut down the listener socket gracefully.  I could add a bunch of logic for that, but that would defeat the purpose of the demo, which is to show the minimal amount of code to set things up.

I don't think I'm going to fix this  in the demo code.  If you want to do this yourself, just change the run.sh script to rm the path to the ipc socket first.
