### ISSUE TITLE
Debug TLS issue?

### ISSUE THREAD

**Issue by sb10** [nanomsg/mangos#94]
I've been using rep/req over TCP just fine, and am trying to switch to tls+tcp, but the req (client) end can't Recv.

I do something like (err handling skipped for brevity, but no errors generated except at the end):

    sock, _ := req.NewSocket()
    sock.SetOption(mangos.OptionMaxRecvSize, 0)
    sock.SetOption(mangos.OptionRecvDeadline, timeout)
    sock.AddTransport(tlstcp.NewTransport())
    tlsConfig := &tls.Config{}
    caCert, _ := ioutil.ReadFile(caFile)
    certPool := x509.NewCertPool()
    certPool.AppendCertsFromPEM(caCert)
    tlsConfig.RootCAs = certPool
    // tlsConfig.InsecureSkipVerify = true
    dialOpts := make(map[string]interface{})
    dialOpts[mangos.OptionTLSConfig] = tlsConfig
    sock.DialOptions("tls+tcp://localhost:11301", dialOpts)
    [...]
    resp, err := sock.Recv()

With InsecureSkipVerify line uncommented it works, but with it commented out, the Recv() err is a generic `receive time out`. How do I get more information on what is really going wrong?

The rep (server) end seems fine. I do something like (again, err handling excluded):

    sock, _ := rep.NewSocket()
    sock.SetOption(mangos.OptionMaxRecvSize, 0)
    sock.SetOption(mangos.OptionRaw, true)
    sock.SetOption(mangos.OptionRecvDeadline, ServerInterruptTime)
    sock.AddTransport(tlstcp.NewTransport())
    cer, _ := tls.LoadX509KeyPair(serverPemFile, serverKeyFile)
    tlsConfig := &tls.Config{Certificates: []tls.Certificate{cer}}
    listenOpts := make(map[string]interface{})
    listenOpts[mangos.OptionTLSConfig] = tlsConfig
    sock.ListenOptions("tls+tcp://0.0.0.0:11301", listenOpts)

 I create the certs like this:

    func GenerateCerts(caFile, serverPemFile, serverKeyFile string) error {
    	// key for root CA
    	rootKey, err := rsa.GenerateKey(rand.Reader, 2048)
    	if err != nil {
    		return err
    	}

    	// cert for root CA, self-signed
    	rootCertTmpl, err := certTemplate()
    	if err != nil {
    		return err
    	}
    	rootCertTmpl.IsCA = true
    	rootCertTmpl.KeyUsage = x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature
    	rootCertTmpl.ExtKeyUsage = []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth}
    	rootCert, err := createCert(rootCertTmpl, rootCertTmpl, &rootKey.PublicKey, rootKey, caFile)
    	if err != nil {
    		return err
    	}

    	// key for server
    	serverKey, err := rsa.GenerateKey(rand.Reader, 2048)
    	if err != nil {
    		return err
    	}

    	// cert for server, signed by root CA
    	servCertTmpl, err := certTemplate()
    	if err != nil {
    		return err
    	}
    	servCertTmpl.KeyUsage = x509.KeyUsageDigitalSignature
    	servCertTmpl.ExtKeyUsage = []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth}
    	_, err = createCert(servCertTmpl, rootCert, &serverKey.PublicKey, rootKey, serverPemFile)
    	if err != nil {
    		return err
    	}

    	// store the server's key
    	keyOut, err := os.OpenFile(serverKeyFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
    	if err != nil {
    		return err
    	}
    	err = pem.Encode(keyOut, &pem.Block{
    		Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(serverKey),
    	})
    	if err != nil {
    		return err
    	}
    	return keyOut.Close()
    }

    // certTemplate creates a certificate template with a random serial number,
    // valid from now until validFor.
    func certTemplate() (*x509.Certificate, error) {
    	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
    	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
    	if err != nil {
    		return nil, errors.New("failed to generate serial number: " + err.Error())
    	}

    	template := x509.Certificate{
    		SerialNumber:          serialNumber,
    		Subject:               pkix.Name{Organization: []string{"my org"}},
    		SignatureAlgorithm:    x509.SHA256WithRSA,
    		NotBefore:             time.Now(),
    		NotAfter:              time.Now().Add(validFor),
    		IPAddresses:           []net.IP{net.ParseIP("0.0.0.0"), net.ParseIP("127.0.0.1")},
    		DNSNames:              []string{"localhost"},
    		BasicConstraintsValid: true,
    	}
    	return &template, nil
    }

    // createCert creates a certificate given a template, signing it against its
    // parent, and saving the cert in PEM format to certPath.
    func createCert(template, parentCert *x509.Certificate, publicKey interface{}, parentPrivateKey interface{}, certPath string) (*x509.Certificate, error) {
    	certDER, err := x509.CreateCertificate(rand.Reader, template, parentCert, publicKey, parentPrivateKey)
    	if err != nil {
    		return nil, err
    	}

    	// parse the resulting certificate so we can use it again
    	cert, err := x509.ParseCertificate(certDER)
    	if err != nil {
    		return nil, err
    	}

    	// save in PEM format
    	b := pem.Block{Type: "CERTIFICATE", Bytes: certDER}
    	certOut, err := os.Create(certPath)
    	if err != nil {
    		err = fmt.Errorf("creation of certificate file [%s] failed: %s", certPath, err)
    		return nil, err
    	}
    	err = pem.Encode(certOut, &b)
    	if err != nil {
    		return nil, err
    	}
    	err = certOut.Close()
    	return cert, err
    }

Any thoughts on how I can get it to work?

**Comment by gdamore** [comment]
Btw, the inline tests now include full up certificate verification without doing InsecureSkipVerify.
